FROM python:3.11-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app

COPY frontend/streamlit_app/requirements.txt /app/requirements.txt
RUN pip install --upgrade pip && pip install --no-cache-dir -r /app/requirements.txt

COPY frontend/streamlit_app /app/frontend/streamlit_app

EXPOSE 8501

CMD ["streamlit", "run", "/app/frontend/streamlit_app/app.py", "--server.port=8501", "--server.address=0.0.0.0"]
